steps:
- name: gcr.io/cloud-builders/git
  args: ['--version']
- name: gcr.io/cloud-builders/docker
  args: ['--version']
- name: gcr.io/cloud-builders/gcloud
  args: ['--version']
- name: gcr.io/cloud-builders/npm
  args: ['--version']
- name: gcr.io/cloud-builders/git
  args: ['--help']
- name: gcr.io/cloud-builders/docker
  args: ['--help']
- name: gcr.io/cloud-builders/bazel
  args: ['--help']
- name: gcr.io/cloud-builders/gcloud
  args: ['--help']
- name: gcr.io/cloud-builders/npm
  args: ['--help']

